Add Entity Embedding Layer To Bert and Roberta
boostcampaitech2/klue-level2-nlp-14 pull request #35
Opened 2021-10-06 06:27 UTC by Amber-Chaeeunk

###  1. Bert entity embedding layer
#### 1.1 모델 사용법
- configs파일 ModelingArguments/architectures변경 : Entity_layer_BertForSequenceClassification

#### 1.2 추가한 클래스 (경로: solution/models/modeling_bert.py)
- Entity_layer_BertEmbeddings
- Entity_layer_BertModel
- Entity_layer_BertForSequenceClassification

 ###  2. RoBerta entity embedding layer추가 모델 사용법
#### 2.1 모델 사용법
- configs파일 ModelingArguments/architectures변경 : Entity_layer_RoBertaForSequenceClassification

#### 2.2 추가한 클래스 (경로: solution/models/modeling_roberta.py)
- Entity_layer_RobertaEmbeddings
- Entity_layer_RobertaModel
- Entity_layer_RobertaForSequenceClassification

2021-10-09 04:42 UTC, jinmang2 requested changes
- Name Convention을 huggingface에 맞게 작성해주시기 바랍니다.
  e.g., `BertForSequenceClassificatoinWithEntityEmbedding`
- 코드를 확장성있게 짜시기 바랍니다.
  e.g., `self.config.vocab_size` + 1

2021-10-09 17:12 UTC, jinmang2 reviewed
아래 사항을 변경했습니다.
- Conflict 방지를 위해 몇몇 폴더 및 내용을 수정했습니다. (prevent conflict 커밋 참고)
- modeling_bert 파일의 객체를 조금 수정했습니다.
    - for loop의 비효율적인 코드를 제거했습니다.
- modeling_roberta 파일을 제거했습니다.
- entity embedding을 위해 새로운 preprocessing code와 data collator를 추가했습니다.

이번엔 저 혼자 review하지만 궁금한 점 있으면 커밋 내역 및 @jinmang2 에게 질문 주시면 되고
이 후 MRC 대회에선 최소 두 명의 reviewer를 두도록 하겠습니다.

2021-10-09 17:12 UTC, jinmang2 approved these changes

2021-10-09 17:12 UTC, merged

2021-11-07 15:20 UTC, Amber-Chaeeunk commented
embedding에 필요한 entity_ids 생성 위치를 data collator로 잘 잡아주셔서 감사합니다👍 
다만, entity위치를 찾기 위해 모든 token을 확인하는 불필요한 for loop을 추가하셨는데, 이 부분은 기존에 구현한 방식처럼 index를 사용하는 것이 효율적일 것 같습니다. review감사드립니다 (우연히 확인해서 답변이 너무 늦었네요)

2021-11-07 17:10 UTC, jinmang2 commented
Entity 위치를 잡기 위해 모든 token을 확인하는 불필요한 loop코드가 어디를 말씀하시는걸까요?

2021-11-07 17:13 UTC, jinmang2 commented
혹시라도 get_entity_embedding 함수를 보고 말씀하신거라면, index로 하시는게 빠를 순 있겠죠. 그러나 기존에 채은님께서 구현하신 코드는 forward에서 돌기 때문에 지금 코드 대비 속도가 매우 떨어집니다. 저 함수는 map을 통해 병렬적으로 처리되기 때문에 index나 for liop이나 전체적인 틀에서 큰 차이는 없을 것 같네요!

2021-11-07 17:17 UTC, jinmang2 commented
저도 이게 코드본지가 오래되서 가물가물하네요 ㅎㅎ 지적해주실 때 코드라인을 따주시면 더 자세한 피드백이 가능할 것 같습니다. (그리고 효율적이라고 생각하시는 근거도 추가로 말씀해주시는게 더 좋은 토론이 될 것 같아요. 라인을 짚어주시면서요)

늦게라도 확인해주셔서 감사합니다!

2022-06-16 06:00 UTC, Amber-Chaeeunk commented
> 혹시라도 get_entity_embedding 함수를 보고 말씀하신거라면, index로 하시는게 빠를 순 있겠죠. 그러나 기존에 채은님께서 구현하신 코드는 forward에서 돌기 때문에 지금 코드 대비 속도가 매우 떨어집니다. 저 함수는 map을 통해 병렬적으로 처리되기 때문에 index나 for liop이나 전체적인 틀에서 큰 차이는 없을 것 같네요!

네 get_entity_embdedding 함수 말한 것 맞습니다. entity_ids 생성 위치를 forward에서 짠 코드는 data collator로 위치를 잘 잡아주셔서 감사하다고 말씀드렸어요 하하^^  제가 말한 부분은 get_entity_embdedding 함수를 인덱스 잡아서 접근하게 짜두었는데 for문 전체 token을 다 탐색하는 방식으로 바꾸셔서 말씀 드렸던 것 같네요. 너무 늦게 확인했지만 답변이 되셨길 바랍니다.